/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package rms.clone.resources;

/**
 *
 * @author ian
 */
public class lists {
    public static String[] ANDROID_BRANDS_LIST = {
        "Samsung",
        "Xiaomi",
        "Oppo",
        "Vivo",
        "Google Pixel",
        "Motorola",
        "OnePlus",
        "Sony",
        "Nokia (HMD)",
        "Lenovo",
        "Asus",
        "Nothing",
        "Realme",
        "Infinix",
        "Tecno",
        "ZTE",
        "TCL (Alcatel)",
        "Sharp",
        "Kyocera",
        "Fairphone",
        "Blackview",
        "Cubot",
        "Doogee",
        "Hisense",
        "Panasonic",
        "Zebra",
        "Honeywell",
        "Datalogic",
         "Huawei (pre-2019)",
         "Other"
    };
    
        public static String[] APPLE_DEVICE_LIST = {
            "iPhone",
            "iPad"
        };
        
        
        public static String[] FLIP_PHONE_BRANDS = {
    "Samsung",
    "Motorola",
    "Nokia",
    "Oppo",
    "LG",
    "Kyocera",
    "Alcatel",
    "Sharp",
    "TCL",
    "CAT",
    "Sonim",
    "ZTE",
    "Sony Ericsson",
    "Pantech",
    "Siemens",
    "Philips",
    "Tiptel",
    "Hyundai",
    "Xiaomi",
    "Honor",
    "Google",
    "OnePlus",
    "Huawei",
    "Vivo",
    "Nubia",
    "Schok",
    "ALT MIVE"
};
         public static String[] PHONE_TYPE_LIST = {
             
             
             
           "Apple - Phone",
             "Apple - Tablet",
             "Samsung - Phone (Foldable and non-foldable)",
             "Samsung - Tablet",
             "Other Android - Phone (Foldable and non-foldable)",
             "Other Android - Tablet",
             "Flip Phone"
             
             
         };
         
         
         
         public static final String[] APPLE_PHONE_MODELS = {
    "iPhone",
    "iPhone 3G",
    "iPhone 3GS",
    "iPhone 4",
    "iPhone 4s",
    "iPhone 5",
    "iPhone 5c",
    "iPhone 5s",
    "iPhone 6",
    "iPhone 6 Plus",
    "iPhone 6s",
    "iPhone 6s Plus",
    "iPhone SE",
    "iPhone 7",
    "iPhone 7 Plus",
    "iPhone 8",
    "iPhone 8 Plus",
    "iPhone X",
    "iPhone XR",
    "iPhone XS",
    "iPhone XS Max",
    "iPhone 11",
    "iPhone 11 Pro",
    "iPhone 11 Pro Max",
    "iPhone SE (2nd generation)",
    "iPhone 12 mini",
    "iPhone 12",
    "iPhone 12 Pro",
    "iPhone 12 Pro Max",
    "iPhone 13 mini",
    "iPhone 13",
    "iPhone 13 Pro",
    "iPhone 13 Pro Max",
    "iPhone SE (3rd generation)",
    "iPhone 14",
    "iPhone 14 Plus",
    "iPhone 14 Pro",
    "iPhone 14 Pro Max",
    "iPhone 15",
    "iPhone 15 Plus",
    "iPhone 15 Pro",
    "iPhone 15 Pro Max",
    "iPhone 16",
    "iPhone 16 Plus",
    "iPhone 16 Pro",
    "iPhone 16 Pro Max",
    "iPhone 16e",
    "iPhone 17",
     "iPhone 17 Pro",
      "iPhone 17 Air",
       "iPhone 17e",
                
};
         
         
         public static final String[] SAMSUNG_PHONE_MODELS = {
             
             //Flagship Android Phones
    "Samsung Galaxy S",
    "Samsung Galaxy S II",
    "Samsung Galaxy S III",
    "Samsung Galaxy S4",
    "Samsung Galaxy S5",
    "Samsung Galaxy S6",
    "Samsung Galaxy S6 Edge",
    "Samsung Galaxy S6 Edge+",
    "Samsung Galaxy S7",
    "Samsung Galaxy S7 Edge",
    "Samsung Galaxy S8",
    "Samsung Galaxy S8+",
    "Samsung Galaxy S9",
    "Samsung Galaxy S9+",
    "Samsung Galaxy S10e",
    "Samsung Galaxy S10",
    "Samsung Galaxy S10+",
    "Samsung Galaxy S10 5G",
    "Samsung Galaxy S20",
    "Samsung Galaxy S20+",
    "Samsung Galaxy S20 Ultra",
    "Samsung Galaxy S20 FE",
    "Samsung Galaxy S21",
    "Samsung Galaxy S21+",
    "Samsung Galaxy S21 Ultra",
    "Samsung Galaxy S21 FE",
    "Samsung Galaxy S22",
    "Samsung Galaxy S22+",
    "Samsung Galaxy S22 Ultra",
    "Samsung Galaxy S23",
    "Samsung Galaxy S23+",
    "Samsung Galaxy S23 Ultra",
    "Samsung Galaxy S23 FE",
    "Samsung Galaxy S24",
    "Samsung Galaxy S24+",
    "Samsung Galaxy S24 Ultra",
    "Samsung Galaxy S24 FE",
    "Samsung Galaxy S25",
    "Samsung Galaxy S25+",
    "Samsung Galaxy S25 Ultra",
    "Samsung Galaxy S25 Edge",

    
    
    // Business Samsuung Phones 
    "Samsung Galaxy Note",
    "Samsung Galaxy Note II",
    "Samsung Galaxy Note 3",
    "Samsung Galaxy Note 4",
    "Samsung Galaxy Note Edge",
    "Samsung Galaxy Note 5",
    "Samsung Galaxy Note 7",
    "Samsung Galaxy Note FE",
    "Samsung Galaxy Note 8",
    "Samsung Galaxy Note 9",
    "Samsung Galaxy Note 10",
    "Samsung Galaxy Note 10+",
    "Samsung Galaxy Note 10+ 5G",
    "Samsung Galaxy Note 20",
    "Samsung Galaxy Note 20 Ultra",

    
    //Foldable Samsung Phones
    "Samsung Galaxy Fold",
    "Samsung Galaxy Z Fold 2",
    "Samsung Galaxy Z Fold 3",
    "Samsung Galaxy Z Fold 4",
    "Samsung Galaxy Z Fold 5",
    "Samsung Galaxy Z Fold 6",
    "Samsung Galaxy Z Fold 7",
    "Samsung Galaxy Z Flip",
    "Samsung Galaxy Z Flip 5G",
    "Samsung Galaxy Z Flip 3",
    "Samsung Galaxy Z Flip 4",
    "Samsung Galaxy Z Flip 5",
    "Samsung Galaxy Z Flip 6",
    "Samsung Galaxy Z Flip 7",
    "Samsung Galaxy Z Flip 7 FE",

    
    
        // mixutre of affordable and mid-range Samsung Phones

    
    "Samsung Galaxy A01",
    "Samsung Galaxy A02",
    "Samsung Galaxy A02s",
    "Samsung Galaxy A03",
    "Samsung Galaxy A03s",
    "Samsung Galaxy A04",
    "Samsung Galaxy A04e",
    "Samsung Galaxy A04s",
    "Samsung Galaxy A05",
    "Samsung Galaxy A05s",
    "Samsung Galaxy A06",
    "Samsung Galaxy A10",
    "Samsung Galaxy A10e",
    "Samsung Galaxy A10s",
    "Samsung Galaxy A11",
    "Samsung Galaxy A12",
    "Samsung Galaxy A13",
    "Samsung Galaxy A14",
    "Samsung Galaxy A15",
    "Samsung Galaxy A16",
    "Samsung Galaxy A20",
    "Samsung Galaxy A20e",
    "Samsung Galaxy A20s",
    "Samsung Galaxy A21",
    "Samsung Galaxy A21s",
    "Samsung Galaxy A22",
    "Samsung Galaxy A23",
    "Samsung Galaxy A24",
    "Samsung Galaxy A25",
    "Samsung Galaxy A26",
    "Samsung Galaxy A30",
    "Samsung Galaxy A30s",
    "Samsung Galaxy A31",
    "Samsung Galaxy A32",
    "Samsung Galaxy A33",
    "Samsung Galaxy A34",
    "Samsung Galaxy A35",
    "Samsung Galaxy A36",
    "Samsung Galaxy A40",
    "Samsung Galaxy A40s",
    "Samsung Galaxy A41",
    "Samsung Galaxy A42",
    "Samsung Galaxy A50",
    "Samsung Galaxy A50s",
    "Samsung Galaxy A51",
    "Samsung Galaxy A52",
    "Samsung Galaxy A52s",
    "Samsung Galaxy A53",
    "Samsung Galaxy A54",
    "Samsung Galaxy A55",
    "Samsung Galaxy A56",
    "Samsung Galaxy A60",
    "Samsung Galaxy A70",
    "Samsung Galaxy A70s",
    "Samsung Galaxy A71",
    "Samsung Galaxy A72",
    "Samsung Galaxy A73",
    "Samsung Galaxy A80",
    "Samsung Galaxy A90 5G",

    
    // mixutre of budget and mid-range Samsung Phones
    "Samsung Galaxy M01",
    "Samsung Galaxy M02",
    "Samsung Galaxy M02s",
    "Samsung Galaxy M10",
    "Samsung Galaxy M10s",
    "Samsung Galaxy M11",
    "Samsung Galaxy M12",
    "Samsung Galaxy M13",
    "Samsung Galaxy M14",
    "Samsung Galaxy M15",
    "Samsung Galaxy M20",
    "Samsung Galaxy M21",
    "Samsung Galaxy M22",
    "Samsung Galaxy M23",
    "Samsung Galaxy M30",
    "Samsung Galaxy M30s",
    "Samsung Galaxy M31",
    "Samsung Galaxy M31s",
    "Samsung Galaxy M32",
    "Samsung Galaxy M33",
    "Samsung Galaxy M34",
    "Samsung Galaxy M35",
    "Samsung Galaxy M40",
    "Samsung Galaxy M51",
    "Samsung Galaxy M52",
    "Samsung Galaxy M53",
    "Samsung Galaxy M54",
    "Samsung Galaxy M55",
    "Samsung Galaxy M62",

    
    // Fan Series Phones
    "Samsung Galaxy F02s",
    "Samsung Galaxy F04",
    "Samsung Galaxy F12",
    "Samsung Galaxy F13",
    "Samsung Galaxy F14",
    "Samsung Galaxy F15",
    "Samsung Galaxy F22",
    "Samsung Galaxy F23",
    "Samsung Galaxy F34",
    "Samsung Galaxy F41",
    "Samsung Galaxy F42",
    "Samsung Galaxy F52",
    "Samsung Galaxy F54",
    "Samsung Galaxy F55",

    
    //budget Samsuung Phones
    "Samsung Galaxy J1",
    "Samsung Galaxy J2",
    "Samsung Galaxy J2 Prime",
    "Samsung Galaxy J3",
    "Samsung Galaxy J3 Prime",
    "Samsung Galaxy J4",
    "Samsung Galaxy J4+",
    "Samsung Galaxy J5",
    "Samsung Galaxy J5 Prime",
    "Samsung Galaxy J6",
    "Samsung Galaxy J6+",
    "Samsung Galaxy J7",
    "Samsung Galaxy J7 Prime",
    "Samsung Galaxy J7 Pro",
    "Samsung Galaxy J8"
};
         
         
        
        public static final String[] SAMSUNG_TABLET_MODELS = {
    "Samsung Galaxy Tab",
    "Samsung Galaxy Tab 7.0 Plus",
    "Samsung Galaxy Tab 7.7",
    "Samsung Galaxy Tab 8.9",
    "Samsung Galaxy Tab 10.1",

    "Samsung Galaxy Tab 2 7.0",
    "Samsung Galaxy Tab 2 10.1",

    "Samsung Galaxy Tab 3 7.0",
    "Samsung Galaxy Tab 3 8.0",
    "Samsung Galaxy Tab 3 10.1",
    "Samsung Galaxy Tab 3 Lite 7.0",

    "Samsung Galaxy Tab 4 7.0",
    "Samsung Galaxy Tab 4 8.0",
    "Samsung Galaxy Tab 4 10.1",

    "Samsung Galaxy Tab Pro 8.4",
    "Samsung Galaxy Tab Pro 10.1",
    "Samsung Galaxy Tab Pro 12.2",

    "Samsung Galaxy Tab S 8.4",
    "Samsung Galaxy Tab S 10.5",
    "Samsung Galaxy Tab S2 8.0",
    "Samsung Galaxy Tab S2 9.7",
    "Samsung Galaxy Tab S3",
    "Samsung Galaxy Tab S4",
    "Samsung Galaxy Tab S5e",
    "Samsung Galaxy Tab S6",
    "Samsung Galaxy Tab S6 Lite",
    "Samsung Galaxy Tab S7",
    "Samsung Galaxy Tab S7+",
    "Samsung Galaxy Tab S7 FE",
    "Samsung Galaxy Tab S8",
    "Samsung Galaxy Tab S8+",
    "Samsung Galaxy Tab S8 Ultra",
    "Samsung Galaxy Tab S9",
    "Samsung Galaxy Tab S9+",
    "Samsung Galaxy Tab S9 Ultra",
    "Samsung Galaxy Tab S9 FE",
    "Samsung Galaxy Tab S9 FE+",
    "Samsung Galaxy Tab S10+",
    "Samsung Galaxy Tab S10 Ultra",
    "Samsung Galaxy Tab S10 FE",
    "Samsung Galaxy Tab S10 FE+",

    "Samsung Galaxy Tab A 7.0",
    "Samsung Galaxy Tab A 8.0",
    "Samsung Galaxy Tab A 8.4",
    "Samsung Galaxy Tab A 9.7",
    "Samsung Galaxy Tab A 10.1",
    "Samsung Galaxy Tab A 10.5",
    "Samsung Galaxy Tab A7",
    "Samsung Galaxy Tab A7 Lite",
    "Samsung Galaxy Tab A8",
    "Samsung Galaxy Tab A9",
    "Samsung Galaxy Tab A9+",

    "Samsung Galaxy Tab E 7.0",
    "Samsung Galaxy Tab E 8.0",
    "Samsung Galaxy Tab E 9.6",

    "Samsung Galaxy Tab Active",
    "Samsung Galaxy Tab Active 2",
    "Samsung Galaxy Tab Active Pro",
    "Samsung Galaxy Tab Active 3",
    "Samsung Galaxy Tab Active 4 Pro",
    "Samsung Galaxy Tab Active 5",

    "Samsung Galaxy View",
    "Samsung Galaxy View 2",

    "Samsung Galaxy Note 8.0",
    "Samsung Galaxy Note 10.1",
    "Samsung Galaxy Note 10.1 2014 Edition",
    "Samsung Galaxy Note Pro 12.2"
};
        
public static final String[] APPLE_TABLET_MODELS = {
    "iPad",
    "iPad 2",
    "iPad 3rd generation",
    "iPad 4th generation",
    "iPad 5th generation",
    "iPad 6th generation",
    "iPad 7th generation",
    "iPad 8th generation",
    "iPad 9th generation",
    "iPad 10th generation",
    "iPad A16",

    "iPad mini",
    "iPad mini 2",
    "iPad mini 3",
    "iPad mini 4",
    "iPad mini 5th generation",
    "iPad mini 6th generation",
    "iPad mini A17 Pro",

    "iPad Air",
    "iPad Air 2",
    "iPad Air 3rd generation",
    "iPad Air 4th generation",
    "iPad Air 5th generation",
    "iPad Air 11-inch M2",
    "iPad Air 13-inch M2",
    "iPad Air 11-inch M3",
    "iPad Air 13-inch M3",

    "iPad Pro 9.7-inch",
    "iPad Pro 10.5-inch",
    "iPad Pro 11-inch 1st generation",
    "iPad Pro 11-inch 2nd generation",
    "iPad Pro 11-inch 3rd generation",
    "iPad Pro 11-inch 4th generation",
    "iPad Pro 11-inch M4",

    "iPad Pro 12.9-inch 1st generation",
    "iPad Pro 12.9-inch 2nd generation",
    "iPad Pro 12.9-inch 3rd generation",
    "iPad Pro 12.9-inch 4th generation",
    "iPad Pro 12.9-inch 5th generation",
    "iPad Pro 12.9-inch 6th generation",

    "iPad Pro 13-inch M4"
};

public static final String[] ANDROID_TABLET_MODELS_US = {
    // Google
    "Google Pixel Tablet",

    // Amazon Fire tablets - Android-based Fire OS
    "Amazon Fire 7",
    "Amazon Fire HD 8",
    "Amazon Fire HD 8 Plus",
    "Amazon Fire HD 10",
    "Amazon Fire HD 10 Plus",
    "Amazon Fire Max 11",
    "Amazon Fire Kids",
    "Amazon Fire HD 8 Kids",
    "Amazon Fire HD 10 Kids",
    "Amazon Fire HD 10 Kids Pro",

    // Lenovo
    "Lenovo Tab M8",
    "Lenovo Tab M9",
    "Lenovo Tab M10",
    "Lenovo Tab M10 Plus",
    "Lenovo Tab M11",
    "Lenovo Tab P11",
    "Lenovo Tab P11 Plus",
    "Lenovo Tab P11 Pro",
    "Lenovo Tab P12",
    "Lenovo Tab P12 Pro",
    "Lenovo Yoga Tab 11",
    "Lenovo Yoga Tab 13",

    // OnePlus
    "OnePlus Pad",
    "OnePlus Pad 2",
    "OnePlus Pad Go",

    // Motorola
    "Motorola Moto Tab G20",
    "Motorola Moto Tab G62",
    "Motorola Moto Tab G70",
    "Motorola Moto Tab G84",

    // TCL
    "TCL Tab 8",
    "TCL Tab 10",
    "TCL Tab 10 5G",
    "TCL Tab 10L",
    "TCL Tab 10s",
    "TCL NXTPAPER 10s",
    "TCL NXTPAPER 11",
    "TCL NXTPAPER 12 Pro",
    "TCL NXTPAPER 14",

    // Walmart onn.
    "onn. 7 Tablet",
    "onn. 8 Tablet",
    "onn. 10.1 Tablet",
    "onn. 11 Tablet Pro",
    "onn. 12.1 Tablet Pro",

    // Nokia / HMD
    "Nokia T10",
    "Nokia T20",
    "Nokia T21",
    "HMD T21",

    // Xiaomi / Redmi / POCO
    "Xiaomi Pad 5",
    "Xiaomi Pad 6",
    "Xiaomi Pad 6 Pro",
    "Xiaomi Pad 6S Pro",
    "Redmi Pad",
    "Redmi Pad SE",
    "POCO Pad",

    // ASUS
    "ASUS ZenPad 8.0",
    "ASUS ZenPad 10",

    // Acer
    "Acer Iconia Tab",
    "Acer Iconia One",
    "Acer Iconia A10",
    "Acer Iconia P10",

    // Other budget Android tablets commonly sold in the US
    "Alldocube iPlay 50",
    "Alldocube iPlay 50 Mini",
    "Alldocube iPlay 60",
    "Teclast P20HD",
    "Teclast P30",
    "Teclast T40",
    "Blackview Tab 8",
    "Blackview Tab 10",
    "Blackview Tab 12",
    "Blackview Tab 15",
    "DOOGEE T10",
    "DOOGEE T20",
    "DOOGEE T30"
};

public static final String[] ANDROID_PHONE_MODELS_US = {
    // Google Pixel
    "Google Pixel",
    "Google Pixel XL",
    "Google Pixel 2",
    "Google Pixel 2 XL",
    "Google Pixel 3",
    "Google Pixel 3 XL",
    "Google Pixel 3a",
    "Google Pixel 3a XL",
    "Google Pixel 4",
    "Google Pixel 4 XL",
    "Google Pixel 4a",
    "Google Pixel 4a 5G",
    "Google Pixel 5",
    "Google Pixel 5a",
    "Google Pixel 6",
    "Google Pixel 6 Pro",
    "Google Pixel 6a",
    "Google Pixel 7",
    "Google Pixel 7 Pro",
    "Google Pixel 7a",
    "Google Pixel 8",
    "Google Pixel 8 Pro",
    "Google Pixel 8a",
    "Google Pixel 9",
    "Google Pixel 9 Pro",
    "Google Pixel 9 Pro XL",
    "Google Pixel 9 Pro Fold",
    "Google Pixel 9a",
    "Google Pixel Fold",

    // Motorola Moto G
    "Motorola Moto G",
    "Motorola Moto G Power",
    "Motorola Moto G Power 5G",
    "Motorola Moto G Play",
    "Motorola Moto G Stylus",
    "Motorola Moto G Stylus 5G",
    "Motorola Moto G Pure",
    "Motorola Moto G Fast",
    "Motorola Moto G 5G",
    "Motorola Moto G Ace",
    "Motorola Moto G 5G Plus",

    // Motorola Edge
    "Motorola Edge",
    "Motorola Edge+",
    "Motorola Edge 5G UW",
    "Motorola Edge 20",
    "Motorola Edge 30",
    "Motorola Edge 30 Fusion",
    "Motorola Edge 30 Neo",
    "Motorola Edge 30 Ultra",
    "Motorola Edge 40",
    "Motorola Edge 40 Neo",
    "Motorola Edge 50",
    "Motorola Edge 50 Fusion",
    "Motorola Edge 50 Pro",
    "Motorola Edge 50 Ultra",

    // Motorola Razr
    "Motorola Razr",
    "Motorola Razr 5G",
    "Motorola Razr 2022",
    "Motorola Razr 2023",
    "Motorola Razr+ 2023",
    "Motorola Razr 2024",
    "Motorola Razr+ 2024",

    // Motorola other
    "Motorola One",
    "Motorola One 5G",
    "Motorola One 5G Ace",
    "Motorola One Action",
    "Motorola One Fusion+",
    "Motorola One Hyper",
    "Motorola One Macro",
    "Motorola One Power",
    "Motorola One Vision",
    "Motorola Defy",

    // OnePlus
    "OnePlus One",
    "OnePlus 2",
    "OnePlus X",
    "OnePlus 3",
    "OnePlus 3T",
    "OnePlus 5",
    "OnePlus 5T",
    "OnePlus 6",
    "OnePlus 6T",
    "OnePlus 7",
    "OnePlus 7 Pro",
    "OnePlus 7T",
    "OnePlus 7T Pro",
    "OnePlus 8",
    "OnePlus 8 Pro",
    "OnePlus 8T",
    "OnePlus 9",
    "OnePlus 9 Pro",
    "OnePlus 9R",
    "OnePlus 10 Pro",
    "OnePlus 10T",
    "OnePlus 11",
    "OnePlus 12",
    "OnePlus 12R",
    "OnePlus 13",
    "OnePlus 13R",
    "OnePlus Open",

    // OnePlus Nord
    "OnePlus Nord",
    "OnePlus Nord N10 5G",
    "OnePlus Nord N20 5G",
    "OnePlus Nord N20 SE",
    "OnePlus Nord N30 5G",
    "OnePlus Nord N100",
    "OnePlus Nord N200 5G",
    "OnePlus Nord N300 5G",

    // Nothing
    "Nothing Phone 1",
    "Nothing Phone 2",
    "Nothing Phone 2a",
    "Nothing Phone 2a Plus",
    "Nothing Phone 3a",
    "Nothing Phone 3a Pro",
    "CMF Phone 1",

    // Sony Xperia
    "Sony Xperia 1",
    "Sony Xperia 1 II",
    "Sony Xperia 1 III",
    "Sony Xperia 1 IV",
    "Sony Xperia 1 V",
    "Sony Xperia 1 VI",
    "Sony Xperia 5",
    "Sony Xperia 5 II",
    "Sony Xperia 5 III",
    "Sony Xperia 5 IV",
    "Sony Xperia 5 V",
    "Sony Xperia 10",
    "Sony Xperia 10 II",
    "Sony Xperia 10 III",
    "Sony Xperia 10 IV",
    "Sony Xperia 10 V",
    "Sony Xperia 10 VI",
    "Sony Xperia PRO",
    "Sony Xperia PRO-I",

    // ASUS
    "ASUS ROG Phone",
    "ASUS ROG Phone II",
    "ASUS ROG Phone 3",
    "ASUS ROG Phone 5",
    "ASUS ROG Phone 5s",
    "ASUS ROG Phone 6",
    "ASUS ROG Phone 6 Pro",
    "ASUS ROG Phone 7",
    "ASUS ROG Phone 7 Ultimate",
    "ASUS ROG Phone 8",
    "ASUS ROG Phone 8 Pro",
    "ASUS Zenfone 6",
    "ASUS Zenfone 7",
    "ASUS Zenfone 8",
    "ASUS Zenfone 8 Flip",
    "ASUS Zenfone 9",
    "ASUS Zenfone 10",
    "ASUS Zenfone 11 Ultra",

    // TCL
    "TCL 10L",
    "TCL 10 Pro",
    "TCL 10 5G UW",
    "TCL 20 SE",
    "TCL 20 Pro 5G",
    "TCL 30 V 5G",
    "TCL 30 XE 5G",
    "TCL 40 XE 5G",
    "TCL 40 XL",
    "TCL 50 XL 5G",
    "TCL 50 XE 5G",
    "TCL Stylus 5G",

    // Nokia / HMD
    "Nokia 1.3",
    "Nokia 2.3",
    "Nokia 2.4",
    "Nokia 3.4",
    "Nokia 5.3",
    "Nokia 5.4",
    "Nokia 6",
    "Nokia 6.1",
    "Nokia 6.2",
    "Nokia 7.1",
    "Nokia 7.2",
    "Nokia 8.3 5G",
    "Nokia C100",
    "Nokia C110",
    "Nokia C200",
    "Nokia C210",
    "Nokia G10",
    "Nokia G20",
    "Nokia G50",
    "Nokia G100",
    "Nokia G300",
    "Nokia X100",
    "Nokia XR20",
    "Nokia XR21",
    "HMD Pulse",
    "HMD Pulse+",
    "HMD Pulse Pro",
    "HMD Vibe",

    // LG
    "LG G6",
    "LG G7 ThinQ",
    "LG G8 ThinQ",
    "LG G8X ThinQ",
    "LG V30",
    "LG V35 ThinQ",
    "LG V40 ThinQ",
    "LG V50 ThinQ",
    "LG V60 ThinQ",
    "LG Velvet",
    "LG Wing",
    "LG Stylo 4",
    "LG Stylo 5",
    "LG Stylo 6",
    "LG K30",
    "LG K40",
    "LG K51",
    "LG K92 5G",

    // HTC
    "HTC One M8",
    "HTC One M9",
    "HTC 10",
    "HTC U11",
    "HTC U12+",
    "HTC U Ultra",
    "HTC Desire 22 Pro",

    // ZTE / Nubia
    "ZTE Axon 7",
    "ZTE Axon 10 Pro",
    "ZTE Axon 20 5G",
    "ZTE Axon 30",
    "ZTE Axon 30 Ultra",
    "ZTE Axon 40 Ultra",
    "ZTE Blade A3",
    "ZTE Blade A7",
    "ZTE Blade A51",
    "ZTE Blade Vantage",
    "Nubia RedMagic 5G",
    "Nubia RedMagic 6",
    "Nubia RedMagic 7",
    "Nubia RedMagic 8 Pro",
    "Nubia RedMagic 9 Pro",

    // BLU
    "BLU G50",
    "BLU G60",
    "BLU G70",
    "BLU G90",
    "BLU G91",
    "BLU G91 Pro",
    "BLU G93",
    "BLU Vivo X",
    "BLU Vivo XI",
    "BLU Vivo XL",
    "BLU Studio Mini",
    "BLU Studio X",

    // CAT rugged phones
    "CAT S41",
    "CAT S42",
    "CAT S48c",
    "CAT S52",
    "CAT S61",
    "CAT S62",
    "CAT S62 Pro",

    // Fairphone / Unihertz / other unlocked niche Android phones
    "Fairphone 4",
    "Fairphone 5",
    "Unihertz Jelly 2",
    "Unihertz Jelly Star",
    "Unihertz Titan",
    "Unihertz Titan Pocket",
    "Unihertz Tank",
    "Unihertz Tank 2"
};


public static final String[] OLD_STYLE_FLIP_PHONE_MODELS = {
    // Motorola
    "Motorola RAZR V3",
    "Motorola RAZR V3i",
    "Motorola RAZR V3m",
    "Motorola RAZR V3c",
    "Motorola RAZR V3xx",
    "Motorola RAZR2 V8",
    "Motorola RAZR2 V9",
    "Motorola RAZR2 V9m",
    "Motorola KRZR K1",
    "Motorola KRZR K1m",
    "Motorola PEBL U6",
    "Motorola V60",
    "Motorola V180",
    "Motorola V188",
    "Motorola V220",
    "Motorola V300",
    "Motorola V330",
    "Motorola V400",
    "Motorola V551",
    "Motorola V557",
    "Motorola V635",
    "Motorola W315",
    "Motorola W385",
    "Motorola W490",
    "Motorola Adventure V750",
    "Motorola Tundra VA76r",
    "Motorola Barrage V860",
    "Motorola Gleam",

    // LG
    "LG VX3200",
    "LG VX3300",
    "LG VX3450",
    "LG VX5200",
    "LG VX5300",
    "LG VX5400",
    "LG VX5500",
    "LG VX6100",
    "LG VX7000",
    "LG VX8100",
    "LG VX8300",
    "LG VX8350",
    "LG VX8600",
    "LG VX8700",
    "LG Chocolate Flip",
    "LG Decoy",
    "LG Glance",
    "LG Revere",
    "LG Revere 2",
    "LG Revere 3",
    "LG Exalt",
    "LG Exalt LTE",
    "LG Wine",
    "LG Wine II",
    "LG Wine Smart",
    "LG Classic Flip",
    "LG B470",
    "LG 441G",
    "LG 450",

    // Samsung
    "Samsung SGH-X427",
    "Samsung SGH-X495",
    "Samsung SGH-X497",
    "Samsung SGH-E315",
    "Samsung SGH-E317",
    "Samsung SGH-E335",
    "Samsung SGH-E635",
    "Samsung SGH-T309",
    "Samsung SGH-T319",
    "Samsung SGH-T609",
    "Samsung SGH-A437",
    "Samsung SGH-A707 Sync",
    "Samsung SGH-A737",
    "Samsung SGH-A837 Rugby",
    "Samsung SCH-A670",
    "Samsung SCH-A790",
    "Samsung SCH-U340",
    "Samsung SCH-U410",
    "Samsung SCH-U430",
    "Samsung SCH-U540",
    "Samsung SCH-U550",
    "Samsung SCH-U640 Convoy",
    "Samsung Convoy 2",
    "Samsung Convoy 3",
    "Samsung Convoy 4",
    "Samsung Alias",
    "Samsung Alias 2",
    "Samsung Rugby II",
    "Samsung Rugby III",
    "Samsung T159",
    "Samsung T259",

    // Nokia
    "Nokia 6101",
    "Nokia 6102",
    "Nokia 6131",
    "Nokia 6126",
    "Nokia 6085",
    "Nokia 6350",
    "Nokia 6650 Fold",
    "Nokia 2720 Fold",
    "Nokia 2760",
    "Nokia 3710 Fold",
    "Nokia 7020",
    "Nokia 7510 Supernova",
    "Nokia 7200",
    "Nokia 7270",

    // Sony Ericsson
    "Sony Ericsson Z500a",
    "Sony Ericsson Z520a",
    "Sony Ericsson Z525a",
    "Sony Ericsson Z530i",
    "Sony Ericsson Z550a",
    "Sony Ericsson Z710i",
    "Sony Ericsson W300i",
    "Sony Ericsson W350",
    "Sony Ericsson W380",
    "Sony Ericsson W508",

    // Sanyo / Sprint-era flip phones
    "Sanyo SCP-200",
    "Sanyo SCP-2300",
    "Sanyo SCP-2400",
    "Sanyo SCP-2700",
    "Sanyo Katana",
    "Sanyo Katana II",
    "Sanyo Katana LX",
    "Sanyo Katana Eclipse",
    "Sanyo M1",
    "Sanyo Pro-200",
    "Sanyo Pro-700",

    // Kyocera
    "Kyocera KX1 SoHo",
    "Kyocera KX2 Koi",
    "Kyocera KX5 Slider Remix",
    "Kyocera K312",
    "Kyocera K323",
    "Kyocera DuraXV",
    "Kyocera DuraXV LTE",
    "Kyocera DuraXV Extreme",
    "Kyocera DuraXE",
    "Kyocera DuraXE Epic",

    // Alcatel / TCL style feature flips
    "Alcatel GO FLIP",
    "Alcatel GO FLIP 2",
    "Alcatel GO FLIP 3",
    "Alcatel GO FLIP 4",
    "Alcatel MyFlip",
    "Alcatel MyFlip 2",
    "Alcatel SMARTFLIP",
    "Alcatel QUICKFLIP",
    "TCL Flip",
    "TCL Flip 2",
    "TCL Flip Pro",
    "TCL Classic",

    // ZTE
    "ZTE Cymbal",
    "ZTE Cymbal LTE",
    "ZTE Cymbal 2",
    "ZTE Z222",
    "ZTE Z223",
    "ZTE Z233",
    "ZTE Altair 2",

    // Pantech
    "Pantech Breeze",
    "Pantech Breeze II",
    "Pantech Breeze III",
    "Pantech Crossover",
    "Pantech Jest",
    "Pantech Jest 2",

    // BlackBerry flip-style
    "BlackBerry Pearl Flip 8220",
    "BlackBerry Pearl Flip 8230",

    // Senior / simple flip phones
    "Jitterbug Flip",
    "Jitterbug Flip2",
    "Lively Flip",
    "Consumer Cellular Link",
    "Consumer Cellular Link II",
    "Consumer Cellular Verve Snap",

    // Other classic-style flip phones
    "UTStarcom CDM7025",
    "UTStarcom CDM7126",
    "Audiovox CDM8910",
    "Audiovox CDM8940",
    "Casio G'zOne Boulder",
    "Casio G'zOne Ravine",
    "Casio G'zOne Ravine 2",
    "Casio G'zOne Rock",
    "Casio G'zOne Type-S",
    "Casio G'zOne Type-V",
    "Sonim XP3",
    "Sonim XP3plus",
    "CAT S22 Flip",
    "Coolpad Snap",
    "Coolpad Belleza",
    "Coolpad Belleza 2",
    "Orbic Journey V",
    "Orbic Journey L",
    "Orbic Journey Pro"
};
    
}
