/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rms.clone.softphone.UI;

import classes.Softphone;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import webphone.*;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;
import rms.clone.main.business.vars;
import java.util.TimerTask;
import rms.clone.main.UI.main.RMS_Clone_CSR;
 
    import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import rms.clone.main.UI.submain.search_customer;


/**
 *
 * @author ischrauth
 */
public class UI extends javax.swing.JFrame {

    /**
     * Creates new form softphone
     */
    public UI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        online_offline_bttn = new javax.swing.JButton();
        online_pannel = new javax.swing.JPanel();
        offline_online_txt = new javax.swing.JLabel();
        timeInStatus_txt = new javax.swing.JLabel();
        status_dd = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        disconect_bttn_txt = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        falName_txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        phoneNumber_txt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        acctNumber_txt = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        online_offline_bttn.setText("Go Online");
        online_offline_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                online_offline_bttnActionPerformed(evt);
            }
        });

        online_pannel.setBackground(new java.awt.Color(204, 204, 204));

        offline_online_txt.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N

        timeInStatus_txt.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        timeInStatus_txt.setText("00:00:00");

        status_dd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lunch", "Break", "ACW", "Training", "Nesting Training", "Mentoring", "Other Task", "Supervisor", "Initial Launch" }));
        status_dd.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                status_ddItemStateChanged(evt);
            }
        });

        jLabel1.setText("Offline reason");

        javax.swing.GroupLayout online_pannelLayout = new javax.swing.GroupLayout(online_pannel);
        online_pannel.setLayout(online_pannelLayout);
        online_pannelLayout.setHorizontalGroup(
            online_pannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(online_pannelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(offline_online_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(online_pannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(online_pannelLayout.createSequentialGroup()
                        .addComponent(timeInStatus_txt)
                        .addGap(193, 193, 193))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, online_pannelLayout.createSequentialGroup()
                        .addGroup(online_pannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(status_dd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(online_pannelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(22, 22, 22)))
                        .addGap(54, 54, 54))))
        );
        online_pannelLayout.setVerticalGroup(
            online_pannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(online_pannelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(online_pannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(online_pannelLayout.createSequentialGroup()
                        .addGroup(online_pannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(offline_online_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timeInStatus_txt))
                        .addGap(0, 35, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, online_pannelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(status_dd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jButton2.setText("Place on hold");
        jButton2.setEnabled(false);

        jButton4.setText("Redial");
        jButton4.setEnabled(false);

        disconect_bttn_txt.setText("Disconect");
        disconect_bttn_txt.setEnabled(false);
        disconect_bttn_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disconect_bttn_txtActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel2.setText("Customer information");

        jLabel3.setText("Phone Number");

        jLabel4.setText("First & Last name");

        jLabel5.setText("Account number");

        jMenu1.setText("File");

        jMenuItem1.setText("SIP Settings");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Incoming call settings");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(online_pannel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(disconect_bttn_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(acctNumber_txt))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(falName_txt))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(phoneNumber_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(online_offline_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(online_pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(online_offline_bttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(disconect_bttn_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(phoneNumber_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(falName_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(acctNumber_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    webphone wobj = new webphone();
        private long startTime;
        ClockListener clock = new ClockListener();
    Timer timer = new Timer(53, clock);
    boolean isOnline = false;
    
    String currentPhoneNumber = "";


    
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        
        
   
       firstLaunch();
        changeCallUIElements("off");
           

       
        
        
    }//GEN-LAST:event_formWindowOpened

    private void online_offline_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_online_offline_bttnActionPerformed



if (!isOnline) {
      //stop the offline counter
            isOnline = true;
              phoneNumber_txt.setText("");
        falName_txt.setText("");
               if (vars.selectedCx != null) {
                      RMS_Clone_CSR.reset();
               }
            
            // subscribe once (or guard so you don’t set it multiple times)
wobj.API_SetNotificationListener(new RingNotificationListener()); // required to get events :contentReference[oaicite:1]{index=1}

// Disable JVoIP built-in GUI / popup dialogs
wobj.API_SetParameter("iscommandline", "true");   // run without built-in GUI
wobj.API_SetParameter("hasgui", "false");         // no built-in GUI at all
wobj.API_SetParameter("hasincomingcall popup", "0"); // disable Accept/Reject popup  :contentReference[oaicite:1]{index=1}
wobj.API_SetParameter("hasincomingcallpopup", "0"); // disable Accept/Reject popup  :contentReference[oaicite:1]{index=1}

// Old parameter name mentioned in docs (typo in docs, but still valid)
wobj.API_SetParameter("hasincomigcall", "0");     // safety


// IMPORTANT: don’t let new calls replace/steal the current call
wobj.API_SetParameter("allowreplace", "0");

// IMPORTANT: reject any new incoming call while already in call
wobj.API_SetParameter("rejectonbusy", "1");


            wobj.API_Start();
            updateClock();
            startTime = System.currentTimeMillis();

            timer.stop();

            online_pannel.setBackground(Color.GREEN);
            offline_online_txt.setText("ONLINE");

            // start the online counter
            startTime = System.currentTimeMillis();
            timer.start();
    online_offline_bttn.setText("Go Offline");
} else {
    
    
    isOnline = false;
     //stop the online counter
            wobj.API_Stop();
            updateClock();
            startTime = 0;
            timer.stop();
            online_pannel.setBackground(Color.RED);
            offline_online_txt.setText("OFFLINE");

            // start the offline counter
            startTime = System.currentTimeMillis();
            timer.start();
   
    online_offline_bttn.setText("Go Online");
}


        // TODO add your handling code here:
    }//GEN-LAST:event_online_offline_bttnActionPerformed

    private void status_ddItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_status_ddItemStateChanged
//
//        if (status_dd.getSelectedItem() == "Online") {
//            online_pannel.setBackground(Color.RED);
//
//            wobj.API_Start();
//            startTime = System.currentTimeMillis();
//            timer.start();
//            offline_online_txt.setText("ONLINE");
//
//        } else if (status_dd.getSelectedItem().toString().contains("Offline")) {
//            //stop the online counter
//            wobj.API_Stop();
//            updateClock();
//            startTime = 0;
//            timer.stop();
//            online_pannel.setBackground(Color.RED);
//            offline_online_txt.setText("OFFLINE");
//
//            // start the offline counter
//            startTime = System.currentTimeMillis();
//            timer.start();
//        }

        // TODO add your handling code here:
    }//GEN-LAST:event_status_ddItemStateChanged

    private void disconect_bttn_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disconect_bttn_txtActionPerformed

        
        
     if (activeLine > 0) {
        wobj.API_Hangup(activeLine, "");
    } else {
        wobj.API_Hangup(-1, ""); // fallback
    }
    activeLine = -1;
    inCall = false;
    disconect_bttn_txt.setEnabled(false);
    changeCallUIElements("acw");

// TODO add your handling code here:
    }//GEN-LAST:event_disconect_bttn_txtActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        new softphone_settings().setVisible(true);


        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField acctNumber_txt;
    private javax.swing.JButton disconect_bttn_txt;
    private javax.swing.JTextField falName_txt;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel offline_online_txt;
    private javax.swing.JButton online_offline_bttn;
    private javax.swing.JPanel online_pannel;
    private javax.swing.JTextField phoneNumber_txt;
    private javax.swing.JComboBox<String> status_dd;
    private javax.swing.JLabel timeInStatus_txt;
    // End of variables declaration//GEN-END:variables

public void firstLaunch() {
    try {
        String SQL = "SELECT ce.csr_id, ce.csr_username, ce.csr_ext, ce.csr_queue, ce.csr_extension_password, ce.uses_default_sip, CASE WHEN ce.uses_default_sip = 1 THEN v.default_sip_address ELSE ce.alt_sip_address END AS sip_address FROM csr_extensions ce CROSS JOIN vars v WHERE ce.csr_id = ?;";
        PreparedStatement pstmt = vars.conn.prepareStatement(SQL);
        pstmt.setInt(1, Integer.parseInt(vars.loggedInUID));
        ResultSet rs = pstmt.executeQuery();

        Softphone s = new Softphone();
        while (rs.next()) {
            s.setSevrer_sip_address(rs.getString("sip_address"));
            s.setSip_username(rs.getString("csr_username"));
            s.setSip_extension(Integer.toString(rs.getInt("csr_ext")));
            s.setSip_password(rs.getString("csr_extension_password"));
        }

        // IMPORTANT: listener first
        wobj.API_SetNotificationListener(new RingNotificationListener());

        // SIP config
        wobj.API_SetParameter("serveraddress", s.getSevrer_sip_address());
        wobj.API_SetParameter("username", s.getSip_username() + s.getSip_extension());
        wobj.API_SetParameter("password", s.getSip_password());

// Disable JVoIP built-in GUI / popup dialogs
wobj.API_SetParameter("hasgui", "false");         // no built-in GUI at all
wobj.API_SetParameter("hasincomingcall popup", "0"); // disable Accept/Reject popup  :contentReference[oaicite:1]{index=1}

// Old parameter name mentioned in docs (typo in docs, but still valid)
wobj.API_SetParameter("hasincomigcall", "0");     // safety


// IMPORTANT: don’t let new calls replace/steal the current call
wobj.API_SetParameter("allowreplace", "0");

// IMPORTANT: reject any new incoming call while already in call
wobj.API_SetParameter("rejectonbusy", "1");

wobj.API_SetParameter("iscommandline", "true");      // run without built-in UI
wobj.API_SetParameter("hasincomingcallpopup", "0"); // disable popup :contentReference[oaicite:1]{index=1}

// optional “silent” knobs (also from docs):
wobj.API_SetParameter("playring", "0");
wobj.API_SetParameter("beeponincoming", "1");


        status_dd.setSelectedIndex(8);

    } catch (Exception ex) {
        Logger.getLogger(UI.class.getName()).log(Level.SEVERE, null, ex);
    }
}




    private void updateClock() {
      SimpleDateFormat date = new SimpleDateFormat("mm:ss");

        Date elapsed = new Date(System.currentTimeMillis() - startTime);
        timeInStatus_txt.setText(date.format(elapsed));
    }

    private class ClockListener implements ActionListener {
        @Override
        public void actionPerformed(ActionEvent e) {
            updateClock();
        }
    }
    
    
    
    public void changeCallUIElements(String status) {
        if (status == "onc") {
            
                    online_pannel.setBackground(Color.CYAN);
                               startTime = System.currentTimeMillis();
            timer.start();
            offline_online_txt.setText("ON CALL");
            online_offline_bttn.setEnabled(false);

        }else if (status == "on") {
            isOnline = true;
            
                      

            
            
            
                    online_pannel.setBackground(Color.GREEN);
                               startTime = System.currentTimeMillis();
            timer.start();
            offline_online_txt.setText("ONLINE");
            online_offline_bttn.setEnabled(true);
                disconect_bttn_txt.setEnabled(false);


            
        } else if (status == "off") {
            isOnline = false;
                    online_pannel.setBackground(Color.RED);
                               startTime = System.currentTimeMillis();
            timer.start();
            offline_online_txt.setText("OFFLINE");
            online_offline_bttn.setEnabled(true);

            
        } else if (status == "acw") {
            isOnline = false;
            wobj.API_Stop(-1);
              status_dd.setSelectedIndex(2);
                  online_pannel.setBackground(Color.ORANGE);
                               startTime = System.currentTimeMillis();
            timer.start();
            offline_online_txt.setText("ACW");
            online_offline_bttn.setEnabled(true);
                online_offline_bttn.setText("Go Online");


     
        }
    }
    
    
    
    public String NameFromPhoneNumberInDB(String phoneNumber) {
        
        try {
            String SQL = "Select firstName, middleName, lastName from customer_info where contactPhone1 = ? OR contactPhone2 = ? OR contactPhone3 = ?;";
            
            PreparedStatement ps = vars.conn.prepareStatement(SQL);
            ps.setString(1, phoneNumber);
            ps.setString(2, phoneNumber);
            ps.setString(3, phoneNumber);
            
            ResultSet rs = ps.executeQuery();
            
            
            while (rs.next()) {
                if (rs.getString("middleName").equals(null)) {
                                   return rs.getString("firstName") + " " + rs.getString("lastName");
 
                } else {
                                    return rs.getString("firstName") + " " + rs.getString("middleName") + " " + rs.getString("lastName");

                }
                
                
            }   } catch (SQLException ex) {
            Logger.getLogger(UI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return null;
        
    }
    
    
        public String AccountNumberFromPhoneNumberInDB(String phoneNumber) {
        
        try {
            String SQL = "Select account_number from customer_info where contactPhone1 = ? OR contactPhone2 = ? OR contactPhone3 = ?;";
            
            PreparedStatement ps = vars.conn.prepareStatement(SQL);
            ps.setString(1, phoneNumber);
            ps.setString(2, phoneNumber);
            ps.setString(3, phoneNumber);
            
            ResultSet rs = ps.executeQuery();
            
            
            while (rs.next()) {
                return rs.getString("account_number");
            }   } catch (SQLException ex) {
            Logger.getLogger(UI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return null;
        
        }
private volatile int activeLine = -1;
private volatile boolean inCall = false;

class RingNotificationListener extends SIPNotificationListener {

    @Override
    public void onStatus(SIPNotification.Status e) {
        if (e == null) return;

        final int line = e.getLine();
        if (line <= 0) return;

        // INCOMING RING
        if (e.getStatus() == SIPNotification.Status.STATUS_CALL_RINGING
                && e.getEndpointType() == SIPNotification.Status.DIRECTION_IN) {

            // Busy: reject new call WITHOUT touching the active call
            if (inCall && activeLine > 0) {
                wobj.API_Reject(line);
                return;
            }

            // Mark active line immediately
            activeLine = line;

            // Extract caller fast (NO DB here)
            final String callerDisplay = safe(e.getPeerDisplayname());
            final String callerPeer = safe(e.getPeer());
            final String shownCaller = !callerDisplay.isBlank() ? callerDisplay : callerPeer;

            final String phone = extractPhone(shownCaller);

            // 1) ACCEPT IMMEDIATELY (don't wait for UI/DB)
            wobj.API_Accept(line);

            // 2) Update UI quickly (on EDT)
            javax.swing.SwingUtilities.invokeLater(() -> {
                phoneNumber_txt.setText(phone);
                falName_txt.setText(callerDisplay); // placeholder until DB returns
                acctNumber_txt.setText("");
                disconect_bttn_txt.setEnabled(true);
                changeCallUIElements("onc");
            });

            // 3) Background DB lookup + open your search window (won't block call answering)
            new javax.swing.SwingWorker<Void, Void>() {
                String dbName;
                String dbAcct;

                @Override
                protected Void doInBackground() {
                    dbName = NameFromPhoneNumberInDB(phone);
                    dbAcct = AccountNumberFromPhoneNumberInDB(phone);
                    return null;
                }

                @Override
                protected void done() {
                    javax.swing.SwingUtilities.invokeLater(() -> {
                        if (dbName != null && !dbName.isBlank()) {
                            falName_txt.setText(dbName);
                        }
                        if (dbAcct != null) {
                            acctNumber_txt.setText(dbAcct);
                        }

                        // Auto-search window
                            rms.clone.main.UI.submain.search_customer.autoSearch = true;
                            rms.clone.main.UI.submain.search_customer.autoSearchPhoneNumber = phone;
                        new search_customer().setVisible(true);
                    });
                }
            }.execute();

            return;
        }

        // CONNECTED
        if (e.getStatus() == SIPNotification.Status.STATUS_CALL_CONNECT) {
            if (line == activeLine) {
                inCall = true;
                javax.swing.SwingUtilities.invokeLater(() -> changeCallUIElements("onc"));
            }
            return;
        }

        // FINISHED
        if (e.getStatus() == SIPNotification.Status.STATUS_CALL_FINISHED) {
            if (line == activeLine) {
                activeLine = -1;
                inCall = false;
                javax.swing.SwingUtilities.invokeLater(() -> {
                    disconect_bttn_txt.setEnabled(false);
                    changeCallUIElements("acw");
                });
            }
        }
    }

    private String safe(String s) {
        return s == null ? "" : s.trim();
    }

    private String extractPhone(String raw) {
    if (raw == null || raw.isBlank()) return "";

    String s = raw.trim();

    int dash = s.indexOf(" -");
    if (dash > 0) s = s.substring(0, dash).trim();

    // Strip SIP URI parts
    if (s.startsWith("sip:")) s = s.substring(4);
    int at = s.indexOf('@');
    if (at > 0) s = s.substring(0, at);

    // Keep digits and optional leading +
    s = s.replaceAll("[^0-9+]", "");

    // If it starts with +, treat as international (keep country code)
    if (s.startsWith("+")) {
        return s;
    }

    // No + → digits only
    // US number cases
    if (s.length() == 11 && s.startsWith("1")) {
        // US number with country code → strip leading 1
        return s.substring(1);
    }

    if (s.length() == 10) {
        // Standard US number
        return s;
    }

    // Foreign number without + (best effort: add +)
    if (s.length() > 10) {
        return "+" + s;
    }

    // Fallback (short/invalid numbers)
    return s;
}
    }
}