/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rms.clone.main.UI.submain;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import rms.clone.main.UI.main.RMS_Clone_CSR;
import rms.clone.main.business.vars;

/**
 *
 * @author ianschrauth
 */
public class discounts extends javax.swing.JFrame {

    /**
     * Creates new form discounts
     */
    public discounts() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        discount_name_txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        discount_use_cb = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        discounts_tbl = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        perm_off_cb = new javax.swing.JRadioButton();
        dol_amt_cb = new javax.swing.JRadioButton();
        full_discount_name_txt = new javax.swing.JTextField();
        perc_ammt = new javax.swing.JTextField();
        dl_ammt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        discount_desc = new javax.swing.JTextArea();
        apply_to_cart_bttn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Discount Name");

        jLabel2.setText("Discount Use");

        discount_use_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select A Discount use--", "-Phones-", "Apple Phones", "Android Phones", "Flip Phones", "-Accessories-", "Apple Phone Cases", "Apple Phone Screen Protectors", "Old Apple Phone Chargers", "Other Apple Phone Accessories ", "Android Phone Cases", "Android Phone Screen Protectors", "Android/New Apple Phone Chargers", "Other Android Phone Accessories ", "-Bluetooth-", "Bluetooth Speakers", "Bluetooth Headphones", "Other Accessories" }));
        discount_use_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discount_use_cbActionPerformed(evt);
            }
        });

        discounts_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Type of Accessory", "Total off"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        discounts_tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                discounts_tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(discounts_tbl);

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Full Discount Name");

        perm_off_cb.setText("Percentage off");
        perm_off_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perm_off_cbActionPerformed(evt);
            }
        });

        dol_amt_cb.setText("Dollar Amount off");

        dl_ammt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dl_ammtActionPerformed(evt);
            }
        });

        jLabel4.setText("Full Discount Description");

        discount_desc.setColumns(20);
        discount_desc.setRows(5);
        jScrollPane2.setViewportView(discount_desc);

        apply_to_cart_bttn.setText("Apply to cart");
        apply_to_cart_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apply_to_cart_bttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(discount_name_txt))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(discount_use_cb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(full_discount_name_txt)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(perm_off_cb)
                                            .addComponent(dol_amt_cb))
                                        .addGap(19, 19, 19)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(dl_ammt, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                            .addComponent(perc_ammt)))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(apply_to_cart_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(discount_name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(discount_use_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(full_discount_name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(perm_off_cb)
                            .addComponent(perc_ammt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dol_amt_cb)
                            .addComponent(dl_ammt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(apply_to_cart_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
            public static DefaultTableModel discounts_tbl_dtm;

            
            public static Map<String, String> descriptions = new HashMap<String, String>();
       

            
            
            
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try {

    discounts_tbl_dtm.setRowCount(0);

    ResultSet rs;
    PreparedStatement ps;

    String SQL = "SELECT * FROM discounts";

    if (!discount_name_txt.getText().strip().isEmpty()) {

        SQL += " WHERE discount_name LIKE ?";
        ps = vars.conn.prepareStatement(SQL);
        ps.setString(1, "%" + discount_name_txt.getText() + "%");

    } 
    else if (
        !discount_use_cb.getSelectedItem().equals("--Select A Discount use--") &&
        !discount_use_cb.getSelectedItem().equals("-Phones-") &&
        !discount_use_cb.getSelectedItem().equals("-Accessories-") &&
        !discount_use_cb.getSelectedItem().equals("-Bluetooth-")
    ) {

        SQL += " WHERE discount_use = ?";
        ps = vars.conn.prepareStatement(SQL);
        ps.setString(1, discount_use_cb.getSelectedItem().toString());

    } 
    else {
        ps = vars.conn.prepareStatement(SQL);
    }

    rs = ps.executeQuery();

    while (rs.next()) {

        double percOff_number = rs.getDouble("discount_perc_off");
        double dollarOff_number = rs.getDouble("discount_usd_off");

        Object[] row;

        if (dollarOff_number == -1.0) {
            row = new Object[]{
                rs.getString("discount_name"),
                rs.getString("discount_use"),
                percOff_number + "%"
            };
        } 
        else {
            row = new Object[]{
                rs.getString("discount_name"),
                rs.getString("discount_use"),
                "$" + dollarOff_number
            };
        }

        descriptions.put(rs.getString("discount_name"), rs.getString("discount_description"));
        
        
        discounts_tbl_dtm.addRow(row);
    }

} catch (SQLException ex) {
    Logger.getLogger(discounts.class.getName()).log(Level.SEVERE, null, ex);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        discounts_tbl_dtm = (DefaultTableModel) discounts_tbl.getModel();


        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void apply_to_cart_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apply_to_cart_bttnActionPerformed

        double orig_total = RMS_Clone_CSR.billTotal;
        
        
double round1_perc_off = 0;
        
        boolean applies =  rms.clone.main.business.actions.checkIfDiscountAppliesToCart(RMS_Clone_CSR.cart_model);
        
         if (perm_off_cb.isSelected() && (applies)) {
            double perc_ammt_temp = Double.parseDouble(perc_ammt.getText().toString()) * 0.01;
          round1_perc_off = orig_total * perc_ammt_temp;
          orig_total = orig_total - round1_perc_off;
     
         
          
       
        } else if (dol_amt_cb.isSelected() && (applies)) {
            orig_total = orig_total - Double.parseDouble(dl_ammt.getText());
        } else if (!applies) {
             System.out.println("Discount does not apply to this order.");
             
        }
         
         
         
         
         
         
         
          if (perm_off_cb.isSelected()) {
          Object[] row_item = {"D", "DISCOUNT", round1_perc_off, 1, false};
   RMS_Clone_CSR.cart_model.addRow(row_item);
   RMS_Clone_CSR.discountTotal += round1_perc_off;
RMS_Clone_CSR.cw.rebind();
    this.dispose();

          } else if (dol_amt_cb.isSelected()) {
                        Object[] row_item = {"D", "DISCOUNT", Double.parseDouble(dl_ammt.getText()), 1, false};
   RMS_Clone_CSR.cart_model.addRow(row_item);
   RMS_Clone_CSR.discountTotal += Double.parseDouble(dl_ammt.getText());
RMS_Clone_CSR.cw.rebind();
    this.dispose();

          }
         
         
         
         
       

 
          



        // TODO add your handling code here:
    }//GEN-LAST:event_apply_to_cart_bttnActionPerformed

    private void discounts_tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_discounts_tblMouseClicked

        int row = discounts_tbl.getSelectedRow();
        int column_name = 0;
        int column_discountType = 2;
        
        String itemName = discounts_tbl.getModel().getValueAt(row, column_name).toString();
        String discountType = discounts_tbl.getModel().getValueAt(row, column_discountType).toString();
        

            full_discount_name_txt.setText(itemName);
            discount_desc.setText(descriptions.get(itemName));


        
        if (discountType.contains("$")) {
            dol_amt_cb.setSelected(true);
            perm_off_cb.setSelected(false);
            dl_ammt.setText(discountType.replace("$", ""));
            perc_ammt.setText("");
            
        } else {
                    dol_amt_cb.setSelected(false);
            perm_off_cb.setSelected(true);
            perc_ammt.setText(discountType.replace("$", ""));
            dl_ammt.setText("");
        }
        
        
        
        
        
 



        // TODO add your handling code here:
    }//GEN-LAST:event_discounts_tblMouseClicked

    private void perm_off_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perm_off_cbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perm_off_cbActionPerformed

    private void dl_ammtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dl_ammtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dl_ammtActionPerformed

    private void discount_use_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discount_use_cbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_discount_use_cbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(discounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(discounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(discounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(discounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new discounts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton apply_to_cart_bttn;
    private javax.swing.JTextArea discount_desc;
    private javax.swing.JTextField discount_name_txt;
    private javax.swing.JComboBox<String> discount_use_cb;
    private javax.swing.JTable discounts_tbl;
    private javax.swing.JTextField dl_ammt;
    private javax.swing.JRadioButton dol_amt_cb;
    private javax.swing.JTextField full_discount_name_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField perc_ammt;
    private javax.swing.JRadioButton perm_off_cb;
    // End of variables declaration//GEN-END:variables

  
}
