/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rms.clone.main.UI.submain;

import classes.Phone_plans;
import java.sql.PreparedStatement;
import java.awt.Component;
import java.sql.*;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import rms.clone.main.UI.main.RMS_Clone_CSR;
import rms.clone.main.business.actions;
import rms.clone.main.business.vars;

/**
 *
 * @author ianschrauth
 */
public class new_activation extends javax.swing.JFrame {

    /**
     * Creates new form new_activation
     */
    public new_activation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        port_in_rb = new javax.swing.JRadioButton();
        new_number_rb = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        imei_txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        make_txt = new javax.swing.JTextField();
        model_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cost_per_month_txt = new javax.swing.JTextField();
        paid_in_full_cb = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        cost_today_txt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        area_code_txt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        acct_number_txt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        acct_pin_txt = new javax.swing.JTextField();
        accct_zip_code_txt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        plans_cb = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        rest_of_number_txt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        port_in_rb.setText("Port in");
        port_in_rb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                port_in_rbItemStateChanged(evt);
            }
        });

        new_number_rb.setText("New Number");
        new_number_rb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                new_number_rbItemStateChanged(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setText("IMEI");

        imei_txt.setEditable(false);

        jLabel2.setText("Device Make");

        make_txt.setEditable(false);
        make_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                make_txtActionPerformed(evt);
            }
        });

        model_txt.setEditable(false);

        jLabel3.setText("Device Model");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel4.setText("Device Detials");

        jLabel10.setText("Cost per mo.");

        cost_per_month_txt.setEditable(false);

        paid_in_full_cb.setText("Paid in full");
        paid_in_full_cb.setEnabled(false);

        jLabel11.setText("Cost Today");

        cost_today_txt.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(make_txt)
                            .addComponent(imei_txt)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(paid_in_full_cb)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(model_txt)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cost_per_month_txt)
                            .addComponent(cost_today_txt))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jLabel4)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(imei_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(make_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(model_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(paid_in_full_cb)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cost_per_month_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cost_today_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(163, Short.MAX_VALUE))
        );

        jLabel5.setText("Phone number");

        jLabel6.setText("Account Number");

        jLabel7.setText("Account Pin");

        jLabel8.setText("Account Zip Code");

        jLabel9.setText("Chosen Plan");

        jButton1.setText("Save");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(acct_pin_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(plans_cb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(accct_zip_code_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(port_in_rb)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(area_code_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rest_of_number_txt)
                            .addComponent(new_number_rb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(acct_number_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(port_in_rb)
                            .addComponent(new_number_rb))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(area_code_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rest_of_number_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(acct_number_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(acct_pin_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(accct_zip_code_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(plans_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(75, 75, 75)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
   public static String typeOfDevice = "";
    
        public static PreparedStatement ps = null;

    
    private void make_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_make_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_make_txtActionPerformed

    private void port_in_rbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_port_in_rbItemStateChanged

        new_number_rb.setSelected(false);
        area_code_txt.setEditable(true);
        rest_of_number_txt.setEditable(true);
        acct_number_txt.setEditable(true);
        accct_zip_code_txt.setEditable(true);
        acct_pin_txt.setEditable(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_port_in_rbItemStateChanged

    private void new_number_rbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_new_number_rbItemStateChanged
        port_in_rb.setSelected(false);
        
         area_code_txt.setEditable(true);
        rest_of_number_txt.setEditable(false);
        acct_number_txt.setEditable(false);
        accct_zip_code_txt.setEditable(false);
        acct_pin_txt.setEditable(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_new_number_rbItemStateChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

                System.out.println("Window Opened.");

        try {
            String SQL = "Select * from phone_plans where type_of_device = ? AND is_active=true;";
            
            ps = vars.conn.prepareStatement(SQL);
                            System.out.println("Init'd ps.");

            ps.setString(1, typeOfDevice);
                                        System.out.println("added " + typeOfDevice + " as the device type(s).");

            ResultSet rs = ps.executeQuery();
        Map<String, Integer> plans = new HashMap<>();

                                        System.out.println("starting rs");

            while (rs.next()) {
                Phone_plans pp = new Phone_plans();
                pp.setPlanId(rs.getInt("plan_id"));
                System.out.println(rs.getString("plan_name"));
                pp.setPlanName(rs.getString("plan_name"));
                                System.out.println(rs.getString("plan_description"));
                                

                pp.setPlanDescription(rs.getString("plan_description"));
                pp.setActive(rs.getBoolean("is_active"));
                pp.setIfUnlimitedTalkMins(rs.getBoolean("is_unlimited_talk_mins"));
                pp.setMaxNumTalkMins(rs.getInt("max_num_talk_mins"));
                pp.setIfUnlimitedTexts(rs.getBoolean("is_unlimited_texts"));
                pp.setMaxNumTexts(rs.getInt("max_num_texts"));
                pp.setIfUnlimitedData(rs.getBoolean("is_unlimited_data"));
                pp.setMaxDataGb(rs.getInt("max_data_gb"));
                pp.setIfUnlimitedPriorityData(rs.getBoolean("is_unlimited_priority_data"));
                pp.setMaxPriorityDataGb(rs.getInt("max_priority_data_gb"));
                pp.setPrepaid(rs.getBoolean("is_prepaid"));
                pp.setPostpaid(rs.getBoolean("is_postpaid"));
                pp.setTypeOfDevice(rs.getString("type_of_device"));
                plans.put(pp.getPlanName(), pp.getPlanId());
            }
            
            
            for (String key: plans.keySet()) {
                System.out.println(key);
                plans_cb.addItem(key);
            }
       
            
            
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(new_activation.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(new_activation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(new_activation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(new_activation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(new_activation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new new_activation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accct_zip_code_txt;
    private javax.swing.JTextField acct_number_txt;
    private javax.swing.JTextField acct_pin_txt;
    private javax.swing.JTextField area_code_txt;
    public static javax.swing.JTextField cost_per_month_txt;
    public static javax.swing.JTextField cost_today_txt;
    public static javax.swing.JTextField imei_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField make_txt;
    public static javax.swing.JTextField model_txt;
    private javax.swing.JRadioButton new_number_rb;
    public static javax.swing.JCheckBox paid_in_full_cb;
    public static javax.swing.JComboBox<String> plans_cb;
    private javax.swing.JRadioButton port_in_rb;
    private javax.swing.JTextField rest_of_number_txt;
    // End of variables declaration//GEN-END:variables

public void launchWindowWithData(String imei, String make, String model, boolean isPiadUpFront, double price_today, double price_per_month, boolean requiresDownpayment, int downpaymentPerc) {
   
    imei_txt.setText(imei);
    make_txt.setText(make);
    model_txt.setText(model);
    if (isPiadUpFront) {
        paid_in_full_cb.setSelected(true);
        cost_per_month_txt.setText("0.00");
        cost_today_txt.setText(Double.toString(price_today));
    } else {
          paid_in_full_cb.setSelected(false);
      
        
        if (requiresDownpayment) {
            double downpayment_ammt = price_today * (downpaymentPerc * .01);
            double newPricePerMonth = (price_today - downpayment_ammt) / 24;

                    cost_per_month_txt.setText(Double.toString(newPricePerMonth));

                    cost_today_txt.setText(Double.toString(downpayment_ammt));  

        } else {
                                cost_per_month_txt.setText(Double.toString(price_per_month));

                    cost_today_txt.setText("0.00");  

        }
        
        
        new new_activation().setVisible(true);
        
          
    }
    
    
    
    
    
    
    
}



}

