/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rms.clone.main.UI.submain;

import rms.clone.main.UI.main.RMS_Clone_CSR;
import classes.Cx;
import classes.phoneNumbers;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;
import static rms.clone.main.UI.main.RMS_Clone_CSR.pay_bill_bttn;
import rms.clone.main.business.actions;
import rms.clone.main.business.vars;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author iansc
 */
public class search_customer extends javax.swing.JFrame {

    /**
     * Creates new form JFrame
     */
    public search_customer() {
        initComponents();
        tableEnterPressInit();
        searchInit();
    }
    
    
    
    private void searchInit() {

    // Reusable ENTER action
    AbstractAction enterAction = new AbstractAction() {
        @Override
        public void actionPerformed(ActionEvent e) {

            System.out.println("ENTER pressed.");

            boolean hasPhone = !phoneNumber_txt.getText().trim().isEmpty();
            boolean hasAcct = !acct_num_txt.getText().trim().isEmpty();
            boolean hasFullName =
                !fname_txt.getText().trim().isEmpty() &&
                !lname_txt.getText().trim().isEmpty();

            if (hasPhone || hasAcct || hasFullName) {
                System.out.println("Conditions met. Performing action...");
                searchForACX();
            } else {
                System.out.println("Conditions NOT met.");
            }
        }
    };

    // Bind ENTER to all relevant fields
    bindEnterKey(phoneNumber_txt, enterAction);
    bindEnterKey(acct_num_txt, enterAction);
    bindEnterKey(fname_txt, enterAction);
    bindEnterKey(lname_txt, enterAction);
}


// Helper method to reduce repetition
private void bindEnterKey(JComponent comp, AbstractAction action) {
    InputMap im = comp.getInputMap(JComponent.WHEN_FOCUSED);
    ActionMap am = comp.getActionMap();

    im.put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "enterPressed");
    am.put("enterPressed", action);
}
    
    
    
    private void tableEnterPressInit() {
        sleectCustomer_tbl.getInputMap(javax.swing.JComponent.WHEN_FOCUSED)
      .put(javax.swing.KeyStroke.getKeyStroke("ENTER"), "enterPressed");

sleectCustomer_tbl.getActionMap().put("enterPressed", new javax.swing.AbstractAction() {
    @Override
    public void actionPerformed(java.awt.event.ActionEvent e) {
int row = sleectCustomer_tbl.getSelectedRow();
int numberOfTotalRows = sleectCustomer_tbl.getRowCount();
System.out.println("Number of rows: " + numberOfTotalRows);

    if (row != -1) {
        selectCx();
    }
    
    }
});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        phoneNumber_txt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        acct_num_txt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        fname_txt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lname_txt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        sleectCustomer_tbl = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setText("Phone Number");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(phoneNumber_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phoneNumber_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        acct_num_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acct_num_txtActionPerformed(evt);
            }
        });

        jLabel5.setText("Account Number");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(acct_num_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(acct_num_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        jLabel6.setText("First Name");

        jLabel7.setText("Last Name");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(fname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        sleectCustomer_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Phone Number", "Account Number", "First & Last name", "Acct. Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        sleectCustomer_tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sleectCustomer_tblMouseClicked(evt);
            }
        });
        sleectCustomer_tbl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sleectCustomer_tblKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(sleectCustomer_tbl);

        jButton2.setText("Select Customer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 boolean usingAcctNumber = true;
 boolean usingPhoneNumber = true;
 boolean usingFaLName = true;
 List<Cx> cxlist = new ArrayList<Cx>();
 String typeOfAccount = ""; // ACC for Account number, PHO for Phone Number, and FAL ofr first/last name
DefaultTableModel model;
 static Cx cx = null;
 public static Boolean autoSearch = false;
 public static String autoSearchPhoneNumber = "";
 
 
 
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
        searchForACX();
        recordSearch();
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
   
        
        selectCx();
        

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void acct_num_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acct_num_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acct_num_txtActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
//
//        if (vars.selectedCx.equals(null)) {
//                    RMS_Clone_CSR.new_bttn.setEnabled(true);
//
//        }
//        



        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        RMS_Clone_CSR.new_bttn.setEnabled(false);
        
        
        if (autoSearch) {
            phoneNumber_txt.setText(autoSearchPhoneNumber);
            searchForACX();
        }
        
        
        
        
    }//GEN-LAST:event_formWindowOpened

    private void sleectCustomer_tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sleectCustomer_tblMouseClicked

if (evt.getClickCount() == 2) { // Double-click detected
            
            int row = sleectCustomer_tbl.getSelectedRow();

            if (row != -1) {
                

                selectCx();
            }
        }
    



        // TODO add your handling code here:
    }//GEN-LAST:event_sleectCustomer_tblMouseClicked

    private void sleectCustomer_tblKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sleectCustomer_tblKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_sleectCustomer_tblKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(search_customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(search_customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(search_customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(search_customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new search_customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField acct_num_txt;
    private javax.swing.JTextField fname_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lname_txt;
    private javax.swing.JTextField phoneNumber_txt;
    private javax.swing.JTable sleectCustomer_tbl;
    // End of variables declaration//GEN-END:variables

    private void searchForACX() {
model = (DefaultTableModel) sleectCustomer_tbl.getModel();
Component frame = null;


if (acct_num_txt.getText().toString().strip().isEmpty()) {
    usingAcctNumber = false;
}

if (fname_txt.getText().toString().strip().isEmpty() && lname_txt.getText().toString().strip().isEmpty()) {
    usingFaLName = false;
}

if (phoneNumber_txt.getText().toString().strip().isEmpty()) {
    usingPhoneNumber = false;
}
List<Map.Entry<phoneNumbers, Cx>> cxList = new ArrayList<>();


if (usingAcctNumber) {
    cxList = actions.searchCustomer("ACC", "", acct_num_txt.getText().toString(), "", "");
} else if (usingFaLName) {
    cxList = actions.searchCustomer("FAL", "", "", fname_txt.getText().toString(), lname_txt.getText().toString());
} else if (usingPhoneNumber) {
    cxList = actions.searchCustomer("PHO", phoneNumber_txt.getText().toString(), "", "", "");
}

System.out.println("FAL NAME: " + usingFaLName);
System.out.println("Phone Number: " + usingPhoneNumber);
System.out.println("ACCT NUMBER: " + usingAcctNumber);

model.setRowCount(0);

for (Map.Entry<phoneNumbers, Cx> entry : cxList) {
    phoneNumbers ph = entry.getKey();
    Cx cx = entry.getValue();

    Object[] rowData = {
        ph.getPhoneNumber(), // show phoneNumber from phoneNumbers
        cx.getAccountNumber(),
        cx.getFirstName() + " " + cx.getLastName(),
        cx.getAccountType()
    };
    model.addRow(rowData);
}

        }



    
    
    public void selectCx() {
              
int row = sleectCustomer_tbl.getSelectedRow();
if (row < 0) {
    JOptionPane.showMessageDialog(this, "Please select a customer first.");
    return;
}

String phoneNumberFromTable = sleectCustomer_tbl.getModel().getValueAt(row, 0).toString();
String acctNumberFromTable  = sleectCustomer_tbl.getModel().getValueAt(row, 1).toString();

rms.clone.main.business.vars.selectedCx = actions.selectCustomerByAccountNumber(acctNumberFromTable);

if (rms.clone.main.business.vars.selectedCx == null) {
    JOptionPane.showMessageDialog(this, "Could not load customer for phone: " + phoneNumberFromTable);
    return;
}

        
        
        RMS_Clone_CSR.fillInPhoneNumbersTable(acctNumberFromTable);
        RMS_Clone_CSR.getAlerts(acctNumberFromTable);
        RMS_Clone_CSR.getNotes(acctNumberFromTable);
        RMS_Clone_CSR.fillActivePhoneNumbers();
        RMS_Clone_CSR.getServices(phoneNumberFromTable);
        RMS_Clone_CSR.fillInCXInfoInSalesTab();
        RMS_Clone_CSR.add_note_bttn.setEnabled(true);
        RMS_Clone_CSR.setEnabledRecursive(jPanel3, true);
        RMS_Clone_CSR.pay_bill_bttn.setEnabled(true);
                          RMS_Clone_CSR.sales_bttn.setEnabled(true);
                  RMS_Clone_CSR.tender_bttn.setEnabled(true);
                  RMS_Clone_CSR.find_item_bttn.setEnabled(true);

        RMS_Clone_CSR.new_sale_bttn.setEnabled(true);
        RMS_Clone_CSR.send_feedback_bttn.setEnabled(true);

        
        
        
        
        
        this.dispose();
    }

    private void recordSearch() {

        try {
            String SQL = "insert into acct_search_history VALUES(?,?,?,?,?,?,NOW());";
            PreparedStatement ps = vars.conn.prepareStatement(SQL);
            
            ps.setInt(1, 0); // repalce with a randonly generated number
            ps.setInt(2, Integer.parseInt(RMS_Clone_CSR.pid_txt_main.getText()));
            if (usingAcctNumber) {
                ps.setString(3, "Account Number");
            } else if (usingPhoneNumber) {
                ps.setString(3, "Phone Number");
                
            }else {
                ps.setString(3, "Name");
            }
            
            if (sleectCustomer_tbl.getRowCount() == 0) {
                ps.setBoolean(4, false);
            } else {
                                ps.setBoolean(4, true);

            }
            
            ps.setString(5, "PENDING"); // fix witn the account number that pulls up
            ps.setBoolean(6, false); // is false for now. fix when account number aboe is fixed
            
            
            int rs = ps.executeUpdate();
            
          
            
        } catch (SQLException ex) {
            Logger.getLogger(search_customer.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        



    }
    



}
