/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rms.clone.main.UI.submain;

import rms.clone.main.business.vars;


import java.awt.Component;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.table.DefaultTableModel;
import rms.clone.main.UI.main.RMS_Clone_CSR;
import rms.clone.main.business.vars;
import rms.clone.resources.lists;





/**
 *
 * @author ianschrauth
 */
public class trade_in_phone extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(trade_in_phone.class.getName());

    /**
     * Creates new form trade_in_phone
     */
    public trade_in_phone() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        rid_txt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        eligable_txt = new javax.swing.JTextField();
        search_clear_bttn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        no_2 = new javax.swing.JRadioButton();
        yes_2 = new javax.swing.JRadioButton();
        no_3 = new javax.swing.JRadioButton();
        yes_3 = new javax.swing.JRadioButton();
        no_4 = new javax.swing.JRadioButton();
        yes_4 = new javax.swing.JRadioButton();
        no_5 = new javax.swing.JRadioButton();
        yes_5 = new javax.swing.JRadioButton();
        no_6 = new javax.swing.JRadioButton();
        yes_6 = new javax.swing.JRadioButton();
        jButton5 = new javax.swing.JButton();
        new_return_bttn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        phone_make_cb = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        phone_model_cb = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        yes_1 = new javax.swing.JRadioButton();
        no_1 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Trade in ID");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Name", "Item SKU/IMEI", "Date Purchased", "Is Returnable", "Type of item"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel4.setText("Is the device free of any dents?");

        jLabel5.setText("Is the device formatted?");

        jLabel6.setText("Are you able to go through the setup of the device without issues? ");

        jLabel7.setText("Was the device opened or damaged in any other way? ");

        jLabel8.setText("Was the device dropped in liquid, according to the customer? ");

        jLabel9.setText("Trade in value");

        eligable_txt.setEditable(false);

        search_clear_bttn.setText("Search");
        search_clear_bttn.addActionListener(this::search_clear_bttnActionPerformed);

        jButton3.setText("Save");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        no_2.setText("No");
        no_2.addItemListener(this::no_2ItemStateChanged);

        yes_2.setText("Yes");
        yes_2.addItemListener(this::yes_2ItemStateChanged);

        no_3.setText("No");
        no_3.addItemListener(this::no_3ItemStateChanged);

        yes_3.setText("Yes");
        yes_3.addItemListener(this::yes_3ItemStateChanged);

        no_4.setText("No");
        no_4.addItemListener(this::no_4ItemStateChanged);

        yes_4.setText("Yes");
        yes_4.addItemListener(this::yes_4ItemStateChanged);

        no_5.setText("No");
        no_5.addItemListener(this::no_5ItemStateChanged);

        yes_5.setText("Yes");
        yes_5.addItemListener(this::yes_5ItemStateChanged);

        no_6.setText("No");
        no_6.addItemListener(this::no_6ItemStateChanged);

        yes_6.setText("Yes");
        yes_6.addItemListener(this::yes_6ItemStateChanged);

        jButton5.setText("Email return label");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        new_return_bttn.setText("New Return");
        new_return_bttn.addActionListener(this::new_return_bttnActionPerformed);

        jButton2.setText("Suspected Fraud");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jLabel2.setText("Device Make");

        phone_make_cb.addItemListener(this::phone_make_cbItemStateChanged);

        jLabel3.setText("Phone Model");

        jLabel11.setText("Is the device free of any cracks?");

        yes_1.setText("Yes");
        yes_1.addItemListener(this::yes_1ItemStateChanged);

        no_1.setText("No");
        no_1.addItemListener(this::no_1ItemStateChanged);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(search_clear_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(new_return_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rid_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eligable_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(yes_2)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(yes_5)
                                                .addComponent(yes_6))
                                            .addComponent(yes_4)
                                            .addComponent(yes_3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(no_3, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(no_4, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(no_5, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(no_6, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(no_2, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(phone_make_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(phone_model_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(yes_1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(no_1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 4, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(rid_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(new_return_bttn)
                    .addComponent(search_clear_bttn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(phone_make_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(phone_model_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(no_1)
                                .addComponent(yes_1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(yes_2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(yes_3)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(yes_4)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(yes_5)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(yes_6)
                                    .addComponent(jLabel8)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(no_2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(no_3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(no_4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(no_5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(no_6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(eligable_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(9, 9, 9)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Component frame = null;
    Boolean freeOfCracks = null;
    Boolean freeOfDents = null;
    Boolean deviceFormatted = null;
    Boolean setupClear = null;
    Boolean deviceLooksOpened = null;
    Boolean liquidDamaged = null;
    
    private void search_clear_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_clear_bttnActionPerformed

        try {

            if (search_clear_bttn.getText().equals("Search")) {

                String SQL = "Select * from returns where rid = ?";

                PreparedStatement ps = vars.conn.prepareStatement(SQL);

                ps.setString(1, rid_txt.getText());

                ResultSet rs = ps.executeQuery();

                while (rs.next()) {

                    setRadioButtonValue(yes_1, no_1, rs.getBoolean("free_of_cracks"));
                    setRadioButtonValue(yes_2, no_2, rs.getBoolean("free_of_dents"));
                    setRadioButtonValue(yes_3, no_3, rs.getBoolean("device_formatted"));
                    setRadioButtonValue(yes_4, no_4, rs.getBoolean("can_go_through_setup"));
                    setRadioButtonValue(yes_5, no_5, rs.getBoolean("opened"));
                    setRadioButtonValue(yes_6, no_6, rs.getBoolean("liquid_damage"));

                    eligable_txt.setText(Boolean.toString(rs.getBoolean("is_eligable")));
//                    status_cb.setSelectedItem(rs.getString("status"));
                    rid_txt.setEditable(false);
                    new_return_bttn.setEnabled(false);
                }

                search_clear_bttn.setText("Clear");

            } else if (search_clear_bttn.getText().equals("Clear")) {

                yes_1.setSelected(false);
                yes_2.setSelected(false);
                yes_3.setSelected(false);
                yes_4.setSelected(false);
                yes_5.setSelected(false);
                yes_6.setSelected(false);
                no_1.setSelected(false);
                no_2.setSelected(false);
                no_3.setSelected(false);
                no_4.setSelected(false);
                no_5.setSelected(false);
                no_6.setSelected(false);

                rid_txt.setEditable(false);
                eligable_txt.setText("");
//                status_cb.setSelectedIndex(0);
                rid_txt.setText("");
                vars.hasManagerAuth = false;
                new_return_bttn.setEnabled(true);

                search_clear_bttn.setText("Search");

                rid_txt.setEnabled(true);
                new_return_bttn.setEnabled(true);

            }

            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(return_phone.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_search_clear_bttnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String SQL = "Insert into returns values(?,NOW(),?,?,?,?,?,?,?,?,?,?,?,?);";

        boolean free_of_cracks = false;
        boolean free_of_dents = false;
        boolean device_formatted = false;
        boolean can_go_through_setup = false;
        boolean looks_opened = false;
        boolean looks_like_liquid_damage = false;

        if (yes_1.isSelected()) {
            free_of_cracks = true;
        }

        if (yes_2.isSelected()) {
            free_of_dents = true;
        }

        if (yes_3.isSelected()) {
            device_formatted = true;
        }

        if (yes_4.isSelected()) {
            can_go_through_setup = true;
        }

        if (yes_5.isSelected()) {
            looks_opened = true;
        }

        if (yes_6.isSelected()) {
            looks_like_liquid_damage = true;
        }

        //
        //        PreparedStatement ps = vars.conn.prepareStatement(SQL);
        //        ps.setInt(1, Integer.parseInt(rid_txt.getText().toString()));
        //        ps.setString(2, device_type_dd.getSelectedItem().toString());
        //        ps.setBoolean(3, free_of_cracks);
        //        ps.setBoolean(4, free_of_dents);
        //        ps.setBoolean(5, device_formatted);
        //        ps.setBoolean(6, can_go_through_setup);
        //        ps.setBoolean(7, looks_opened);
        //        ps.setBoolean(8, looks_like_liquid_damage);
        //        ps.setString(9, eligable_txt.getText().toString());
        //

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void no_2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_no_2ItemStateChanged
        yes_2.setSelected(false);
        freeOfDents = false;
        canItBeReturned(freeOfCracks, freeOfDents, deviceFormatted, setupClear, deviceLooksOpened, liquidDamaged);

        // TODO add your handling code here:
    }//GEN-LAST:event_no_2ItemStateChanged

    private void yes_2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_yes_2ItemStateChanged
        no_2.setSelected(false);
        freeOfDents = true;
        // TODO add your handling code here:
    }//GEN-LAST:event_yes_2ItemStateChanged

    private void no_3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_no_3ItemStateChanged

        yes_3.setSelected(false);
        deviceFormatted = false;
        canItBeReturned(freeOfCracks, freeOfDents, deviceFormatted, setupClear, deviceLooksOpened, liquidDamaged);

        // TODO add your handling code here:
    }//GEN-LAST:event_no_3ItemStateChanged

    private void yes_3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_yes_3ItemStateChanged
        no_3.setSelected(false);
        deviceFormatted = true;
        canItBeReturned(freeOfCracks, freeOfDents, deviceFormatted, setupClear, deviceLooksOpened, liquidDamaged);

        // TODO add your handling code here:
    }//GEN-LAST:event_yes_3ItemStateChanged

    private void no_4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_no_4ItemStateChanged

        yes_4.setSelected(false);
        setupClear = false;
        canItBeReturned(freeOfCracks, freeOfDents, deviceFormatted, setupClear, deviceLooksOpened, liquidDamaged);

        // TODO add your handling code here:
    }//GEN-LAST:event_no_4ItemStateChanged

    private void yes_4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_yes_4ItemStateChanged
        no_4.setSelected(false);
        setupClear = true;
        canItBeReturned(freeOfCracks, freeOfDents, deviceFormatted, setupClear, deviceLooksOpened, liquidDamaged);

        // TODO add your handling code here:
    }//GEN-LAST:event_yes_4ItemStateChanged

    private void no_5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_no_5ItemStateChanged

        yes_5.setSelected(false);
        deviceLooksOpened = false;
        canItBeReturned(freeOfCracks, freeOfDents, deviceFormatted, setupClear, deviceLooksOpened, liquidDamaged);

        // TODO add your handling code here:
    }//GEN-LAST:event_no_5ItemStateChanged

    private void yes_5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_yes_5ItemStateChanged

        no_5.setSelected(false);
        deviceLooksOpened = true;
        canItBeReturned(freeOfCracks, freeOfDents, deviceFormatted, setupClear, deviceLooksOpened, liquidDamaged);

        // TODO add your handling code here:
    }//GEN-LAST:event_yes_5ItemStateChanged

    private void no_6ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_no_6ItemStateChanged

        yes_6.setSelected(false);
        liquidDamaged = false;
        canItBeReturned(freeOfCracks, freeOfDents, deviceFormatted, setupClear, deviceLooksOpened, liquidDamaged);

        // TODO add your handling code here:
    }//GEN-LAST:event_no_6ItemStateChanged

    private void yes_6ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_yes_6ItemStateChanged

        no_6.setSelected(false);
        liquidDamaged = true;
        canItBeReturned(freeOfCracks, freeOfDents, deviceFormatted, setupClear, deviceLooksOpened, liquidDamaged);

        // TODO add your handling code here:
    }//GEN-LAST:event_yes_6ItemStateChanged

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void new_return_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_return_bttnActionPerformed

        int returnID = Integer.parseInt(rms.clone.main.business.actions.generateAnyID("returns", "rid", false, 'x'));

        rid_txt.setText(Integer.toString(returnID));
        rid_txt.setEnabled(false);
        new_return_bttn.setEnabled(false);
        search_clear_bttn.setText("Clear");
//        chnage_save_sttaus_bttn.setEnabled(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_new_return_bttnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // this is for when the agent feels like the returned device might not be the device sold to them.

        StolenDevicePopup.accountNumber = vars.selectedCx.getAccountNumber();
        StolenDevicePopup.showDeviceCheck();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        
        
        
                    phone_make_cb.setModel(new DefaultComboBoxModel<>(lists.PHONE_TYPE_LIST));

        
        



        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void phone_make_cbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_phone_make_cbItemStateChanged
        // TODO add your handling code here:
        
        
        if (phone_make_cb.getSelectedItem().equals("Apple - Phone")) {
            phone_make_cb.setModel(new DefaultComboBoxModel<>(lists.APPLE_PHONE_MODELS));

        } else  if (phone_make_cb.getSelectedItem().equals("Apple - Tablet")) {
            phone_make_cb.setModel(new DefaultComboBoxModel<>(lists.APPLE_TABLET_MODELS));

        }else  if (phone_make_cb.getSelectedItem().equals("Samsung - Phone (Foldable and non-foldable)")) {
            phone_make_cb.setModel(new DefaultComboBoxModel<>(lists.SAMSUNG_PHONE_MODELS));

        } else  if (phone_make_cb.getSelectedItem().equals("Samsung - Tablet")) {
            phone_make_cb.setModel(new DefaultComboBoxModel<>(lists.SAMSUNG_TABLET_MODELS));

        } else  if (phone_make_cb.getSelectedItem().equals("Other Android - Phone (Foldable and non-foldable)")) {
            phone_make_cb.setModel(new DefaultComboBoxModel<>(lists.ANDROID_PHONE_MODELS_US));

        } else  if (phone_make_cb.getSelectedItem().equals("Other Android - Tablet")) {
            phone_make_cb.setModel(new DefaultComboBoxModel<>(lists.ANDROID_TABLET_MODELS_US));

        } else  if (phone_make_cb.getSelectedItem().equals("Flip Phone")) {
            phone_make_cb.setModel(new DefaultComboBoxModel<>(lists.OLD_STYLE_FLIP_PHONE_MODELS));

        } else {
            
        }
        
   
        
        
    }//GEN-LAST:event_phone_make_cbItemStateChanged

    private void yes_1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_yes_1ItemStateChanged

        no_1.setSelected(false);
        freeOfCracks = true;

        // TODO add your handling code here:
    }//GEN-LAST:event_yes_1ItemStateChanged

    private void no_1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_no_1ItemStateChanged

        yes_1.setSelected(false);
        freeOfCracks = false;
        canItBeReturned(freeOfCracks, freeOfDents, deviceFormatted, setupClear, deviceLooksOpened, liquidDamaged);

        // TODO add your handling code here:
    }//GEN-LAST:event_no_1ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new trade_in_phone().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField eligable_txt;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton new_return_bttn;
    private javax.swing.JRadioButton no_1;
    private javax.swing.JRadioButton no_2;
    private javax.swing.JRadioButton no_3;
    private javax.swing.JRadioButton no_4;
    private javax.swing.JRadioButton no_5;
    private javax.swing.JRadioButton no_6;
    private javax.swing.JComboBox<String> phone_make_cb;
    private javax.swing.JComboBox<String> phone_model_cb;
    private javax.swing.JTextField rid_txt;
    private javax.swing.JButton search_clear_bttn;
    private javax.swing.JRadioButton yes_1;
    private javax.swing.JRadioButton yes_2;
    private javax.swing.JRadioButton yes_3;
    private javax.swing.JRadioButton yes_4;
    private javax.swing.JRadioButton yes_5;
    private javax.swing.JRadioButton yes_6;
    // End of variables declaration//GEN-END:variables


public static Boolean canItBeReturned(Boolean freeOfCracks,Boolean freeOfDents,Boolean freeOfData,Boolean noIssuesDuringSetup,Boolean freeOfOtherDamageOrOpened,Boolean hasLiquidDamage) {
    
        if ((freeOfCracks == null) || (freeOfOtherDamageOrOpened == null) || (hasLiquidDamage == null) || (noIssuesDuringSetup == null) || (freeOfDents == null) || (freeOfData == null)) {

            System.out.println("Form not complete yet");
        // do noting, as form is not complete yet

        }
    
    //default if all of them are checked correclty for denial 
        else if ((!freeOfCracks) || (!freeOfOtherDamageOrOpened) || (hasLiquidDamage) || (!noIssuesDuringSetup) || (!freeOfDents) || (!freeOfData)) {
    return false;
    // defualt if all of them are checked correctly for acceptence 
} else if ((freeOfCracks) || (freeOfOtherDamageOrOpened) || (!hasLiquidDamage) || (noIssuesDuringSetup) || (freeOfDents) || (freeOfData)) {
    return true;
    

// if the device is damaged (screen and dents) but that is it. Will be denied
} else if ((!freeOfCracks) && (!freeOfDents) && (!hasLiquidDamage) && (noIssuesDuringSetup) && (freeOfOtherDamageOrOpened) && (freeOfData)) {
    return false;
    
    
    // if the device is damaged (screen only) but that is it. Will be denied

}else if ((!freeOfCracks) && (freeOfDents) && (!hasLiquidDamage) && (noIssuesDuringSetup) && (freeOfOtherDamageOrOpened) && (freeOfData)) {
    return false;
    
    
    // if the device's data is not wiped, but everything else is fine. Will be denied. 
} else if ((freeOfCracks) && (freeOfDents) && (!hasLiquidDamage) && (noIssuesDuringSetup) && (freeOfOtherDamageOrOpened) && (!freeOfData)) {


    return false;
    
    
    
}
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    return true;
}



public static void setRadioButtonValue(JRadioButton yesButton, JRadioButton noButton, boolean value) {

        if (value) {
            yesButton.setSelected(true);
            noButton.setSelected(false);
        } else {
            yesButton.setSelected(false);
            noButton.setSelected(true);
        }

    }










}
