/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rms.clone.main.UI.manager;



import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import rms.clone.main.business.vars;



/**
 *
 * @author ianschrauth
 */
public class employee_managment extends javax.swing.JFrame {

    /**
     * Creates new form employee_managment
     */
    public employee_managment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        employee_pid_txt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        order_table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fname_txt = new javax.swing.JTextField();
        lname_txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        work_email_txt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        hire_date_txt = new javax.swing.JTextField();
        is_mgr_cb = new javax.swing.JCheckBox();
        is_leadership_cb = new javax.swing.JCheckBox();
        reset_rms_password_bttn = new javax.swing.JButton();
        deactivate_profile_bttn = new javax.swing.JButton();
        franchise_employee_cb = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        save_bttn = new javax.swing.JButton();
        profile_deactivated_cb = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Employee PID");

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        order_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cx Account Number", "Date", "Total", "Includes Device sale", "Includes Acc. Sale"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(order_table);

        jLabel2.setText("First Name");

        jLabel3.setText("Last Name");

        fname_txt.setEnabled(false);

        lname_txt.setEnabled(false);

        jLabel4.setText("Company Email");

        work_email_txt.setEnabled(false);

        jLabel5.setText("Hire Date");

        hire_date_txt.setEnabled(false);

        is_mgr_cb.setText("Is manager");
        is_mgr_cb.setEnabled(false);

        is_leadership_cb.setText("is leadership");
        is_leadership_cb.setEnabled(false);

        reset_rms_password_bttn.setText("Reset RMS Password");
        reset_rms_password_bttn.setEnabled(false);

        deactivate_profile_bttn.setText("Deactivate RMS profile");
        deactivate_profile_bttn.setEnabled(false);

        franchise_employee_cb.setText("Franchise Employee");
        franchise_employee_cb.setEnabled(false);

        jLabel6.setText("Sort by");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Order Date", "Device Sales", "Accessory Sales", "Total (Least to greatest)", "Total (Geatest to least)" }));

        save_bttn.setText("Save Changes");
        save_bttn.setEnabled(false);

        profile_deactivated_cb.setText("Profile deactivated");
        profile_deactivated_cb.setEnabled(false);

        jButton2.setText("Pull Up Order Summary");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(save_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(reset_rms_password_bttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deactivate_profile_bttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(work_email_txt))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(employee_pid_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton1))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2))
                                    .addGap(35, 35, 35)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fname_txt)
                                        .addComponent(lname_txt)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(44, 44, 44)
                                    .addComponent(hire_date_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(is_mgr_cb)
                                        .addComponent(is_leadership_cb))
                                    .addGap(36, 36, 36)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(profile_deactivated_cb)
                                        .addComponent(franchise_employee_cb)))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(employee_pid_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(work_email_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(hire_date_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(is_mgr_cb)
                    .addComponent(franchise_employee_cb))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(is_leadership_cb)
                    .addComponent(profile_deactivated_cb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reset_rms_password_bttn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deactivate_profile_bttn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(save_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
        
        
        
        clearFieldsAndTable();
        
        
        SearchEmployeeRecord(Integer.parseInt(employee_pid_txt.getText().toString()));
        searchForSalesByEmployee(Integer.parseInt(employee_pid_txt.getText()));

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        
 




        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(employee_managment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(employee_managment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(employee_managment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(employee_managment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new employee_managment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deactivate_profile_bttn;
    private javax.swing.JTextField employee_pid_txt;
    private javax.swing.JTextField fname_txt;
    private javax.swing.JCheckBox franchise_employee_cb;
    private javax.swing.JTextField hire_date_txt;
    private javax.swing.JCheckBox is_leadership_cb;
    private javax.swing.JCheckBox is_mgr_cb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lname_txt;
    private javax.swing.JTable order_table;
    private javax.swing.JCheckBox profile_deactivated_cb;
    private javax.swing.JButton reset_rms_password_bttn;
    private javax.swing.JButton save_bttn;
    private javax.swing.JTextField work_email_txt;
    // End of variables declaration//GEN-END:variables

    private void SearchEmployeeRecord(int pid) {
    try {
        String SQL = "SELECT * from company_logins where PID = ?";
        
       PreparedStatement ps =  vars.conn.prepareStatement(SQL);
       
       
        ps.setInt(1, pid);
        
        
        ResultSet rs = ps.executeQuery();
        
        
        while (rs.next()) {
        
        
                fname_txt.setText(rs.getString("agent_fname"));
                lname_txt.setText(rs.getString("agent_lname"));
                work_email_txt.setText(rs.getString("company_email"));
                hire_date_txt.setText(rs.getDate("hire_date").toString());
                
                boolean isManager = rs.getBoolean("is_manager");
                boolean isLeadership = rs.getBoolean("is_leadership");
                boolean franchiseEmployee = rs.getBoolean("is_franchise_employee");
                boolean isActive = rs.getBoolean("is_active");
                
                if (isManager) {
                    is_mgr_cb.setSelected(true);
                }
                if (isLeadership) {
                    is_leadership_cb.setSelected(true);
                }
                if (franchiseEmployee) {
                    franchise_employee_cb.setSelected(true);
                }
                
                
                if (!isActive) {
                    profile_deactivated_cb.setSelected(true);
                }   
            
        }
        
        
        //enable the fields that need to be enabled for editing 
        fname_txt.setEnabled(true);
        lname_txt.setEnabled(true);
        work_email_txt.setEnabled(true);
        is_mgr_cb.setEnabled(true);
        profile_deactivated_cb.setEnabled(true);
        reset_rms_password_bttn.setEnabled(true);
        deactivate_profile_bttn.setEnabled(true);
        save_bttn.setEnabled(true);
            
            
            
            
            
            } catch (SQLException ex) {
                Logger.getLogger(employee_managment.class.getName()).log(Level.SEVERE, null, ex);
            }
   
       




    }

    private void clearFieldsAndTable() {
        
        
        
        DefaultTableModel model_order = (DefaultTableModel) order_table.getModel();

                fname_txt.setText("");
                lname_txt.setText("");
                work_email_txt.setText("");
                hire_date_txt.setText("");
                is_mgr_cb.setSelected(false);
                is_leadership_cb.setSelected(false);
                franchise_employee_cb.setSelected(false);
                profile_deactivated_cb.setSelected(false);
                model_order.setRowCount(0);
          

    }

    private void searchForSalesByEmployee(int employeePID) {
    DefaultTableModel orderHistoryModel = (DefaultTableModel) order_table.getModel();

        
        boolean includesDeviceSale = false;
        boolean includesAccSale = false;
        
        
        try {
            String SQL = "SELECT * FROM transactions_all " +
                    "WHERE pid_of_assosiate = ? " +
                    "AND LOWER(type_of_transaction) LIKE '%sale%'";
            
            
            
            PreparedStatement ps =  vars.conn.prepareStatement(SQL);
            
            
            ps.setInt(1, employeePID);
            
            
            ResultSet rs = ps.executeQuery();
            
        
            
            
            
            while (rs.next()) {
                
                
                    
              if (rs.getString("type_of_transaction").equals("Accessory Sale")) {
                        includesAccSale = true;
                    }
                    
              
               if ((rs.getString("type_of_transaction").contains("Prepaid")) || (rs.getString("type_of_transaction").contains("Postpaid"))) {
                        includesDeviceSale = true;
                    }
                    
               
               
                System.out.println("Type of Transaction: " + rs.getString("type_of_transaction"));
                
                
                
                
                Object[] row = {
                    rs.getString("cx_acct_number"),
                    rs.getString("date_time_of_transaction"),
                    rs.getDouble("grand_total"),
                    includesDeviceSale,
                    includesAccSale
                    
                    
                  
                    
                    
                    
                
                };
                
                  orderHistoryModel.addRow(row);
            }
            
            
        } catch (SQLException ex) {
            System.getLogger(employee_managment.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        


    }
}
